
#if !defined(FPGROWTH_GLOBAL_H_20181210)
#define FPGROWTH_GLOBAL_H_20181210

#define NAMESPACE_ALPHALAB_NAME alpha

#define NAMESPACE_ALPHALAB_BEGIN namespace NAMESPACE_ALPHALAB_NAME {
#define NAMESPACE_ALPHALAB_END }


#endif // FPGROWTH_GLOBAL_H_20181210
